"""ByteBrains backend API.

Run from the ByteBrains project root:
    python -m uvicorn backend.main:app --reload
"""
from __future__ import annotations

import hashlib
import hmac
import os
import secrets
from datetime import date, datetime
from typing import Any

from fastapi import APIRouter, Depends, FastAPI, HTTPException, Query, status
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import inspect, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from .database import Base, engine, get_db
from .Models import (
    Achievement, Application, Assessment, AssessmentAttempt,
    AssessmentQuestion, Certification, Collaboration, Company, Course,
    CourseEnrollment, Department, Education, Event, Experience, Faculty,
    Institution, Internship, InternshipSkill, Mentorship, Notification,
    PortfolioProject, Recommendation, Resume, Skill, SkillGap, Student,
    StudentSkill,
)

app = FastAPI(
    title="ByteBrains API",
    version="1.0.0",
    description="Academia–Industry Collaboration Portal backend.",
)

# Comma-separated frontend origins can be supplied in backend/.env.
def _cors_origins() -> list[str]:
    raw = os.getenv("CORS_ORIGINS", "*").strip()
    return [x.strip() for x in raw.split(",") if x.strip()] or ["*"]

origins = _cors_origins()
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=False if "*" in origins else True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Importing all models above registers them with SQLAlchemy metadata.
# create_all only creates missing tables; it does not migrate existing tables.
@app.on_event("startup")
def create_tables() -> None:
    Base.metadata.create_all(bind=engine)


def _json_value(value: Any) -> Any:
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    return value


def serialize(model: Any) -> dict[str, Any]:
    mapper = inspect(model.__class__)
    return {
        column.key: _json_value(getattr(model, column.key))
        for column in mapper.columns
    }


def serialize_many(rows: list[Any]) -> list[dict[str, Any]]:
    return [serialize(row) for row in rows]


def model_columns(model: Any) -> set[str]:
    return {column.key for column in inspect(model).columns}


def clean_payload(model: Any, payload: dict[str, Any], *, partial: bool = False) -> dict[str, Any]:
    allowed = model_columns(model)
    unknown = sorted(set(payload) - allowed)
    if unknown:
        raise HTTPException(
            status_code=422,
            detail={"message": "Unknown fields", "fields": unknown},
        )
    if not partial:
        # id and server timestamps are generated by the database.
        payload.pop("id", None)
        payload.pop("created_at", None)
        payload.pop("posted_at", None)
        payload.pop("uploaded_at", None)
        payload.pop("generated_at", None)
        payload.pop("attempted_at", None)
        payload.pop("applied_at", None)
        payload.pop("enrolled_at", None)
    return payload


def db_error(exc: IntegrityError) -> HTTPException:
    return HTTPException(
        status_code=400,
        detail="Database constraint failed. Check required fields, unique values, and foreign-key IDs.",
    )


# ---------------------------------------------------------------------------
# Health / database
# ---------------------------------------------------------------------------
@app.get("/", tags=["Health"])
def root():
    return {"status": "ByteBrains backend running", "version": app.version}


@app.get("/health", tags=["Health"])
def health():
    return {"status": "ok"}


@app.get("/db-test", tags=["Health"])
def db_test(db: Session = Depends(get_db)):
    result = db.execute(text("SELECT 1")).scalar()
    return {"database_connected": True, "result": result}


# ---------------------------------------------------------------------------
# Authentication helpers
# ---------------------------------------------------------------------------
# PBKDF2 is used so the backend does not depend on bcrypt/passlib just to boot.
# Passwords are never returned by API responses.
def hash_password(password: str) -> str:
    salt = secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, 310_000)
    return f"pbkdf2_sha256$310000${salt.hex()}${digest.hex()}"


def verify_password(password: str, encoded: str) -> bool:
    try:
        algorithm, rounds, salt_hex, digest_hex = encoded.split("$", 3)
        if algorithm != "pbkdf2_sha256":
            return False
        candidate = hashlib.pbkdf2_hmac(
            "sha256", password.encode(), bytes.fromhex(salt_hex), int(rounds)
        ).hex()
        return hmac.compare_digest(candidate, digest_hex)
    except (ValueError, TypeError):
        return False


def public_user(model: Any) -> dict[str, Any]:
    data = serialize(model)
    data.pop("password_hash", None)
    return data


class AuthRouter:
    def __init__(self, model: Any, prefix: str, label: str):
        self.model = model
        self.router = APIRouter(prefix=prefix, tags=[label])
        self._register()

    def _register(self):
        model = self.model
        router = self.router

        @router.post("/register", status_code=status.HTTP_201_CREATED)
        def register(payload: dict[str, Any], db: Session = Depends(get_db)):
            data = dict(payload)
            password = data.pop("password", None)
            if not password:
                raise HTTPException(422, "password is required")
            if "password_hash" in data:
                data.pop("password_hash")
            data["password_hash"] = hash_password(str(password))
            clean_payload(model, data)
            obj = model(**data)
            db.add(obj)
            try:
                db.commit()
                db.refresh(obj)
            except IntegrityError as exc:
                db.rollback()
                raise db_error(exc)
            return public_user(obj)

        @router.post("/login")
        def login(payload: dict[str, Any], db: Session = Depends(get_db)):
            email = payload.get("email")
            password = payload.get("password")
            if not email or not password:
                raise HTTPException(422, "email and password are required")
            obj = db.query(model).filter(model.email == str(email).strip().lower()).first()
            if not obj or not verify_password(str(password), obj.password_hash):
                raise HTTPException(401, "Invalid email or password")
            return {"authenticated": True, "user": public_user(obj)}


student_auth = AuthRouter(Student, "/auth/student", "Student Auth")
company_auth = AuthRouter(Company, "/auth/company", "Company Auth")
faculty_auth = AuthRouter(Faculty, "/auth/faculty", "Faculty Auth")
app.include_router(student_auth.router)
app.include_router(company_auth.router)
app.include_router(faculty_auth.router)


# ---------------------------------------------------------------------------
# Generic CRUD routes for every ByteBrains entity.
# This gives every table a predictable REST API:
# GET /api/<resource>, GET /api/<resource>/{id}, POST, PATCH, DELETE.
# ---------------------------------------------------------------------------
RESOURCES: dict[str, Any] = {
    "students": Student,
    "companies": Company,
    "faculty": Faculty,
    "skills": Skill,
    "student-skills": StudentSkill,
    "resumes": Resume,
    "internships": Internship,
    "applications": Application,
    "skill-gaps": SkillGap,
    "recommendations": Recommendation,
    "internship-skills": InternshipSkill,
    "portfolio-projects": PortfolioProject,
    "certifications": Certification,
    "education": Education,
    "experiences": Experience,
    "achievements": Achievement,
    "courses": Course,
    "course-enrollments": CourseEnrollment,
    "assessments": Assessment,
    "assessment-questions": AssessmentQuestion,
    "assessment-attempts": AssessmentAttempt,
    "institutions": Institution,
    "departments": Department,
    "events": Event,
    "collaborations": Collaboration,
    "notifications": Notification,
    "mentorships": Mentorship,
}


def register_crud(resource: str, model: Any) -> None:
    router = APIRouter(prefix=f"/api/{resource}", tags=[resource])
    columns = model_columns(model)

    @router.get("")
    def list_items(
        limit: int = Query(50, ge=1, le=200),
        offset: int = Query(0, ge=0),
        db: Session = Depends(get_db),
    ):
        rows = db.query(model).offset(offset).limit(limit).all()
        return {"items": serialize_many(rows), "count": len(rows), "limit": limit, "offset": offset}

    @router.get("/{item_id}")
    def get_item(item_id: int, db: Session = Depends(get_db)):
        obj = db.get(model, item_id)
        if obj is None:
            raise HTTPException(404, f"{resource[:-1].capitalize()} not found")
        return serialize(obj)

    @router.post("", status_code=status.HTTP_201_CREATED)
    def create_item(payload: dict[str, Any], db: Session = Depends(get_db)):
        data = clean_payload(model, dict(payload))
        # Passwords should be supplied through /auth/*/register.
        if "password_hash" in columns and "password" in data:
            data["password_hash"] = hash_password(str(data.pop("password")))
        obj = model(**data)
        db.add(obj)
        try:
            db.commit()
            db.refresh(obj)
        except IntegrityError as exc:
            db.rollback()
            raise db_error(exc)
        return public_user(obj) if "password_hash" in columns else serialize(obj)

    @router.patch("/{item_id}")
    def update_item(item_id: int, payload: dict[str, Any], db: Session = Depends(get_db)):
        obj = db.get(model, item_id)
        if obj is None:
            raise HTTPException(404, f"{resource[:-1].capitalize()} not found")
        data = clean_payload(model, dict(payload), partial=True)
        data.pop("id", None)
        for key, value in data.items():
            if key in {"password_hash"}:
                continue
            setattr(obj, key, value)
        db.add(obj)
        try:
            db.commit()
            db.refresh(obj)
        except IntegrityError as exc:
            db.rollback()
            raise db_error(exc)
        return public_user(obj) if "password_hash" in columns else serialize(obj)

    @router.delete("/{item_id}")
    def delete_item(item_id: int, db: Session = Depends(get_db)):
        obj = db.get(model, item_id)
        if obj is None:
            raise HTTPException(404, f"{resource[:-1].capitalize()} not found")
        db.delete(obj)
        try:
            db.commit()
        except IntegrityError as exc:
            db.rollback()
            raise db_error(exc)
        return {"deleted": True, "id": item_id}

    app.include_router(router)


for _resource, _model in RESOURCES.items():
    register_crud(_resource, _model)


# ---------------------------------------------------------------------------
# Frontend-friendly aliases for the student portal.
# ---------------------------------------------------------------------------
@app.get("/students", tags=["Student Portal"])
def get_students(
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_db),
):
    rows = db.query(Student).offset(offset).limit(limit).all()
    return serialize_many(rows)


@app.get("/students/{student_id}/profile", tags=["Student Portal"])
def student_profile(student_id: int, db: Session = Depends(get_db)):
    student = db.get(Student, student_id)
    if not student:
        raise HTTPException(404, "Student not found")
    return public_user(student)


@app.get("/students/{student_id}/skills", tags=["Student Portal"])
def student_skills(student_id: int, db: Session = Depends(get_db)):
    rows = db.query(StudentSkill).filter(StudentSkill.student_id == student_id).all()
    return serialize_many(rows)


@app.get("/students/{student_id}/applications", tags=["Student Portal"])
def student_applications(student_id: int, db: Session = Depends(get_db)):
    rows = db.query(Application).filter(Application.student_id == student_id).all()
    return serialize_many(rows)


@app.get("/students/{student_id}/portfolio", tags=["Student Portal"])
def student_portfolio(student_id: int, db: Session = Depends(get_db)):
    rows = db.query(PortfolioProject).filter(PortfolioProject.student_id == student_id).all()
    return serialize_many(rows)


@app.get("/students/{student_id}/resume", tags=["Student Portal"])
def student_resume(student_id: int, db: Session = Depends(get_db)):
    rows = db.query(Resume).filter(Resume.student_id == student_id).all()
    return serialize_many(rows)


@app.get("/students/{student_id}/recommendations", tags=["Student Portal"])
def student_recommendations(student_id: int, db: Session = Depends(get_db)):
    rows = db.query(Recommendation).filter(Recommendation.student_id == student_id).all()
    return serialize_many(rows)


@app.get("/internships", tags=["Internships"])
def list_open_internships(
    limit: int = Query(50, ge=1, le=200),
    db: Session = Depends(get_db),
):
    rows = (
        db.query(Internship)
        .filter(Internship.status == "open")
        .order_by(Internship.posted_at.desc())
        .limit(limit)
        .all()
    )
    return serialize_many(rows)

# ---------------------------------------------------------------------------
# Assessment submission used by the Student Portal.
# ---------------------------------------------------------------------------
@app.post("/students/{student_id}/assessments/submit", tags=["Student Portal"])
def submit_assessment(student_id: int, payload: dict[str, Any], db: Session = Depends(get_db)):
    if not db.get(Student, student_id):
        raise HTTPException(404, "Student not found")
    category = str(payload.get("category", "")).strip().lower()
    try:
        score = float(payload.get("score", 0))
        total = int(payload.get("total", 0))
    except (TypeError, ValueError):
        raise HTTPException(422, "Invalid score or total")
    if total <= 0 or score < 0 or score > total:
        raise HTTPException(422, "Invalid score or total")
    names = {"python":"Python Programming","sql":"SQL & Databases","ml":"Machine Learning","aptitude":"Quantitative Aptitude","comm":"Communication Skills"}
    skill_name = names.get(category, category.title())
    if not skill_name:
        raise HTTPException(422, "category is required")
    skill = db.query(Skill).filter(Skill.name.ilike(skill_name)).first()
    if not skill:
        skill = Skill(name=skill_name); db.add(skill); db.flush()
    pct = round(score / total * 100, 2)
    proficiency = "Beginner" if pct < 50 else "Intermediate" if pct < 75 else "Advanced"
    ss = db.query(StudentSkill).filter(StudentSkill.student_id == student_id, StudentSkill.skill_id == skill.id).first()
    if not ss:
        ss = StudentSkill(student_id=student_id, skill_id=skill.id); db.add(ss)
    ss.proficiency = proficiency
    assessment = db.query(Assessment).filter(Assessment.skill_id == skill.id).first()
    if not assessment:
        assessment = Assessment(title=f"{skill_name} Assessment", skill_id=skill.id, total_marks=total, passing_marks=max(1, round(total * .5)))
        db.add(assessment); db.flush()
    attempt = AssessmentAttempt(student_id=student_id, assessment_id=assessment.id, score=score, total_marks=total, percentage=pct, status="passed" if pct >= 50 else "needs_improvement")
    db.add(attempt)
    for gap in db.query(SkillGap).filter(SkillGap.student_id == student_id, SkillGap.missing_skill_id == skill.id).all():
        db.delete(gap)
    if pct < 70:
        db.add(SkillGap(student_id=student_id, missing_skill_id=skill.id, severity="high" if pct < 50 else "medium"))
    db.commit(); db.refresh(attempt)
    return {"attempt_id": attempt.id, "percentage": pct, "proficiency": proficiency}


# ---------------------------------------------------------------------------
# Industry employer workspace routes
# ---------------------------------------------------------------------------
def _skill_names(db: Session, internship_id: int) -> list[str]:
    rows = (db.query(Skill.name)
            .join(InternshipSkill, InternshipSkill.skill_id == Skill.id)
            .filter(InternshipSkill.internship_id == internship_id)
            .order_by(Skill.name)
            .all())
    return [r[0] for r in rows]


def _latest_student_scores(db: Session, student_id: int) -> dict[int, float]:
    attempts = (db.query(AssessmentAttempt)
                .filter(AssessmentAttempt.student_id == student_id)
                .order_by(AssessmentAttempt.attempted_at.desc(), AssessmentAttempt.id.desc())
                .all())
    result: dict[int, float] = {}
    for a in attempts:
        assessment = db.get(Assessment, a.assessment_id)
        if assessment and assessment.skill_id not in result:
            result[assessment.skill_id] = float(a.percentage or 0)
    return result


def _match_for_application(db: Session, application: Application) -> dict[str, Any]:
    skill_rows = (db.query(Skill)
                  .join(InternshipSkill, InternshipSkill.skill_id == Skill.id)
                  .filter(InternshipSkill.internship_id == application.internship_id)
                  .order_by(Skill.name).all())
    scores = _latest_student_scores(db, application.student_id)
    matched, missing, values = [], [], []
    for skill in skill_rows:
        score = scores.get(skill.id, 0)
        if score > 0:
            matched.append(skill.name)
            values.append(score)
        else:
            missing.append(skill.name)
    match_score = round(sum(values) / len(skill_rows), 1) if skill_rows else 0
    student = db.get(Student, application.student_id)
    internship = db.get(Internship, application.internship_id)
    return {
        **serialize(application),
        "student": serialize(student) if student else None,
        "internship": {"id": internship.id, "title": internship.title} if internship else None,
        "match_score": match_score,
        "matched_skills": matched,
        "missing_skills": missing,
    }


def _company_or_404(db: Session, company_id: int) -> Company:
    company = db.get(Company, company_id)
    if not company:
        raise HTTPException(404, "Company not found")
    return company


@app.get("/companies/{company_id}", tags=["Industry"])
def company_detail(company_id: int, db: Session = Depends(get_db)):
    return public_user(_company_or_404(db, company_id))


@app.get("/companies/{company_id}/summary", tags=["Industry"])
def company_summary(company_id: int, db: Session = Depends(get_db)):
    _company_or_404(db, company_id)
    internships = db.query(Internship).filter(Internship.company_id == company_id).all()
    ids = [i.id for i in internships]
    apps = db.query(Application).filter(Application.internship_id.in_(ids)).all() if ids else []
    return {
        "active_postings": sum(1 for i in internships if (i.status or "open").lower() == "open"),
        "applicants": len(apps),
        "shortlisted": sum(1 for a in apps if a.status == "shortlisted"),
        "offers": sum(1 for a in apps if a.status == "offered"),
        "accepted": sum(1 for a in apps if a.status == "accepted"),
    }


@app.get("/companies/{company_id}/internships", tags=["Industry"])
def company_internships(company_id: int, db: Session = Depends(get_db)):
    _company_or_404(db, company_id)
    rows = db.query(Internship).filter(Internship.company_id == company_id).order_by(Internship.posted_at.desc(), Internship.id.desc()).all()
    out = []
    for i in rows:
        data = serialize(i)
        data["skills"] = _skill_names(db, i.id)
        data["application_count"] = db.query(Application).filter(Application.internship_id == i.id).count()
        out.append(data)
    return out


@app.post("/companies/{company_id}/internships", status_code=201, tags=["Industry"])
def create_company_internship(company_id: int, payload: dict[str, Any], db: Session = Depends(get_db)):
    _company_or_404(db, company_id)
    title = str(payload.get("title", "")).strip()
    skills = [str(s).strip() for s in payload.get("required_skills", []) if str(s).strip()]
    if not title or not skills:
        raise HTTPException(422, "title and required_skills are required")
    deadline = payload.get("deadline")
    if isinstance(deadline, str) and deadline:
        try:
            deadline = datetime.fromisoformat(deadline.replace("Z", "+00:00"))
        except ValueError:
            raise HTTPException(422, "Invalid deadline")
    obj = Internship(company_id=company_id, title=title, description=payload.get("description"), location=payload.get("location"), duration=payload.get("duration"), stipend=payload.get("stipend"), mode=payload.get("mode"), deadline=deadline, status=payload.get("status") or "open")
    db.add(obj)
    db.flush()
    for name in skills:
        skill = db.query(Skill).filter(Skill.name.ilike(name)).first()
        if not skill:
            skill = Skill(name=name)
            db.add(skill); db.flush()
        if not db.query(InternshipSkill).filter(InternshipSkill.internship_id == obj.id, InternshipSkill.skill_id == skill.id).first():
            db.add(InternshipSkill(internship_id=obj.id, skill_id=skill.id))
    db.commit(); db.refresh(obj)
    data = serialize(obj); data["skills"] = _skill_names(db, obj.id); data["application_count"] = 0
    return data


@app.patch("/companies/{company_id}/internships/{internship_id}", tags=["Industry"])
def update_company_internship(company_id: int, internship_id: int, payload: dict[str, Any], db: Session = Depends(get_db)):
    _company_or_404(db, company_id)
    obj = db.query(Internship).filter(Internship.id == internship_id, Internship.company_id == company_id).first()
    if not obj: raise HTTPException(404, "Internship not found")
    allowed = {"title","description","location","duration","stipend","mode","status"}
    unknown = set(payload) - allowed
    if unknown: raise HTTPException(422, {"message":"Unknown fields", "fields":sorted(unknown)})
    if "status" in payload and payload["status"] not in {"open","closed"}: raise HTTPException(422,"status must be open or closed")
    for k,v in payload.items(): setattr(obj,k,v)
    db.commit(); db.refresh(obj)
    data=serialize(obj); data["skills"]=_skill_names(db,obj.id); data["application_count"]=db.query(Application).filter(Application.internship_id==obj.id).count(); return data


@app.get("/companies/{company_id}/applications", tags=["Industry"])
def company_applications(company_id: int, db: Session = Depends(get_db)):
    _company_or_404(db, company_id)
    rows = (db.query(Application).join(Internship, Application.internship_id == Internship.id)
            .filter(Internship.company_id == company_id)
            .order_by(Application.applied_at.desc(), Application.id.desc()).all())
    return [_match_for_application(db, a) for a in rows]


@app.patch("/companies/{company_id}/applications/{application_id}", tags=["Industry"])
def update_company_application(company_id: int, application_id: int, payload: dict[str, Any], db: Session = Depends(get_db)):
    _company_or_404(db, company_id)
    app_row = (db.query(Application).join(Internship, Application.internship_id == Internship.id)
               .filter(Application.id == application_id, Internship.company_id == company_id).first())
    if not app_row: raise HTTPException(404, "Application not found")
    new_status = str(payload.get("status", ""))
    if new_status not in {"applied","shortlisted","offered","accepted","rejected"}: raise HTTPException(422,"Invalid application status")
    app_row.status = new_status
    db.commit(); db.refresh(app_row)
    return _match_for_application(db, app_row)
