import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { setStoredCompany } from "@/lib/auth";

export const Route = createFileRoute("/login")({ component: LoginPage });
function LoginPage() {
  const navigate = useNavigate(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function onSubmit(e: React.FormEvent) { e.preventDefault(); if(!email.trim()||!password.trim()){setError("Enter email and password.");return;} setBusy(true);setError(""); try { const result=await api.login(email.trim().toLowerCase(),password); setStoredCompany(result.user); navigate({to:"/industry"}); } catch(err) { const msg=err instanceof Error?err.message:"Unable to sign in"; setError(msg); toast.error(msg); } finally {setBusy(false);} }
  return <div className="min-h-screen bg-background"><header className="border-b border-border bg-card"><div className="mx-auto max-w-[1440px] px-6 py-5"><Link to="/" className="font-display text-xl font-semibold">AICP <span className="text-xs text-muted-foreground">Industry Portal</span></Link></div></header><main className="mx-auto grid max-w-[1000px] gap-12 px-6 py-20 lg:grid-cols-2"><div><p className="label-caps">Employer access</p><h1 className="mt-4 font-display text-5xl font-semibold">Welcome back</h1><div className="mt-6 h-px w-16 bg-accent"/><p className="mt-6 max-w-md text-lg text-muted-foreground">Manage internships, required skills and student applications from one employer workspace.</p></div><div className="rounded-md border border-border bg-card p-8 shadow-card"><h2 className="font-display text-xl font-semibold">Sign in</h2><form className="mt-6 space-y-4" onSubmit={onSubmit}><Field label="Email"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" className="input" placeholder="you@company.com"/></Field><Field label="Password"><input value={password} onChange={e=>setPassword(e.target.value)} type="password" className="input" placeholder="••••••••"/></Field>{error&&<p className="text-sm text-destructive">{error}</p>}<button disabled={busy} className="h-11 w-full rounded-md bg-primary text-sm font-medium text-primary-foreground disabled:opacity-60">{busy?"Signing in…":"Sign in"}</button></form><p className="mt-6 text-sm text-muted-foreground">New organisation? <Link to="/signup" className="text-accent-foreground underline">Create an account</Link></p></div></main></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><label className="label-caps">{label}</label><div className="mt-2">{children}</div></div>}
