import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { api } from "@/lib/api";

export const Route = createFileRoute("/signup")({ component: SignupPage });
function SignupPage(){
 const navigate=useNavigate(); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [industry,setIndustry]=useState(""); const [location,setLocation]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 async function submit(e:React.FormEvent){e.preventDefault();if(!name.trim()||!email.trim()||!password){setError("Organisation, email and password are required.");return;}if(password!==confirm){setError("Passwords do not match.");return;}setBusy(true);setError("");try{await api.register({name:name.trim(),email:email.trim().toLowerCase(),password,industry_type:industry.trim(),location:location.trim()});toast.success("Organisation created. Please sign in.");navigate({to:"/login"});}catch(err){const msg=err instanceof Error?err.message:"Unable to create account";setError(msg);toast.error(msg);}finally{setBusy(false);}}
 return <div className="min-h-screen bg-background"><header className="border-b border-border bg-card"><div className="mx-auto max-w-[1000px] px-6 py-5"><Link to="/" className="font-display text-xl font-semibold">AICP <span className="text-xs text-muted-foreground">Industry Portal</span></Link></div></header><main className="mx-auto max-w-[1000px] px-6 py-16"><div className="mx-auto max-w-xl rounded-md border border-border bg-card p-8 shadow-card"><p className="label-caps">Employer registration</p><h1 className="mt-3 font-display text-4xl font-semibold">Create organisation account</h1><form className="mt-8 grid gap-4 sm:grid-cols-2" onSubmit={submit}><Field label="Organisation"><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Acme Technologies"/></Field><Field label="Industry"><input className="input" value={industry} onChange={e=>setIndustry(e.target.value)} placeholder="Technology"/></Field><Field label="Email"><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="hr@company.com"/></Field><Field label="Location"><input className="input" value={location} onChange={e=>setLocation(e.target.value)} placeholder="Delhi"/></Field><Field label="Password"><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} /></Field><Field label="Confirm password"><input className="input" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} /></Field>{error&&<p className="sm:col-span-2 text-sm text-destructive">{error}</p>}<button disabled={busy} className="sm:col-span-2 h-11 rounded-md bg-primary text-sm font-medium text-primary-foreground disabled:opacity-60">{busy?"Creating…":"Create account"}</button></form><p className="mt-6 text-sm text-muted-foreground">Already registered? <Link to="/login" className="underline">Sign in</Link></p></div></main></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><label className="label-caps">{label}</label><div className="mt-2">{children}</div></div>}
